_format_version: "3.0"

services:
  - name: auth-service
    url: http://auth-service:3000
    routes:
      - name: auth-routes
        paths:
          - /api/auth
        strip_path: true

  - name: crm-service
    url: http://crm-service:3001
    routes:
      - name: crm-routes
        paths:
          - /api/crm
        strip_path: true

  - name: sales-service
    url: http://host.docker.internal:3002
    routes:
      - name: sales-routes
        paths:
          - /api/sales
        strip_path: true

  - name: invoicing-service
    url: http://host.docker.internal:3003
    routes:
      - name: invoicing-routes
        paths:
          - /api/invoicing
        strip_path: true

  - name: inventory-service
    url: http://host.docker.internal:3004
    routes:
      - name: inventory-routes
        paths:
          - /api/inventory
        strip_path: true

  - name: accounting-service
    url: http://host.docker.internal:3005
    routes:
      - name: accounting-routes
        paths:
          - /api/accounting
        strip_path: true

  - name: hrm-service
    url: http://host.docker.internal:3006
    routes:
      - name: hrm-routes
        paths:
          - /api/hrm
        strip_path: true

  - name: workflow-engine
    url: http://host.docker.internal:3007
    routes:
      - name: workflow-routes
        paths:
          - /api/workflow
        strip_path: true
        
  - name: frontend
    url: http://host.docker.internal:12000
    routes:
      - name: frontend-routes
        paths:
          - /app
        strip_path: true

plugins:
  - name: cors
    config:
      origins:
        - "*"
      methods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
        - PATCH
      headers:
        - Accept
        - Accept-Version
        - Content-Length
        - Content-MD5
        - Content-Type
        - Date
        - X-Auth-Token
        - Authorization
      exposed_headers:
        - X-Auth-Token
      credentials: true
      max_age: 3600

  - name: rate-limiting
    config:
      minute: 1000
      policy: local