apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  labels:
    app: auth-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: nextcore/auth-service:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: nextcore-db-credentials
              key: host
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: nextcore-db-credentials
              key: port
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: nextcore-db-credentials
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nextcore-db-credentials
              key: password
        - name: DB_DATABASE
          valueFrom:
            secretKeyRef:
              name: nextcore-db-credentials
              key: database
        - name: JWT_ACCESS_SECRET
          valueFrom:
            secretKeyRef:
              name: nextcore-jwt-secrets
              key: access-secret
        - name: JWT_REFRESH_SECRET
          valueFrom:
            secretKeyRef:
              name: nextcore-jwt-secrets
              key: refresh-secret
        - name: JWT_ACCESS_EXPIRATION
          value: "15m"
        - name: JWT_REFRESH_EXPIRATION
          value: "7d"
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth-service
  ports:
  - port: 80
    targetPort: 3000
  type: ClusterIP