apiVersion: apps/v1
kind: Deployment
metadata:
  name: sales-service
  labels:
    app: sales-service
    component: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sales-service
  template:
    metadata:
      labels:
        app: sales-service
        component: backend
    spec:
      containers:
      - name: sales-service
        image: nextcore/sales-service:latest
        ports:
        - containerPort: 4001
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "4001"
        - name: DB_HOST
          value: "postgresql"
        - name: DB_PORT
          value: "5432"
        - name: DB_USERNAME
          value: "nextcore"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nextcore-secrets
              key: db-password
        - name: DB_DATABASE
          value: "nextcore"
        - name: REDIS_URL
          value: "redis://redis:6379"
        - name: NATS_URL
          value: "nats://nats:4222"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: nextcore-secrets
              key: jwt-secret
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/sales/health
            port: 4001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/sales/health
            port: 4001
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: sales-service
  labels:
    app: sales-service
spec:
  selector:
    app: sales-service
  ports:
  - port: 4001
    targetPort: 4001
    protocol: TCP
  type: ClusterIP