apiVersion: v1
kind: Secret
metadata:
  name: nextcore-db-credentials
type: Opaque
stringData:
  host: "postgres"
  port: "5432"
  username: "nextcore"
  password: "change-me-in-production"
  database: "nextcore"
---
apiVersion: v1
kind: Secret
metadata:
  name: nextcore-jwt-secrets
type: Opaque
stringData:
  access-secret: "change-me-in-production-access-secret"
  refresh-secret: "change-me-in-production-refresh-secret"